#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/Hilbert.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/core.jar:$APPDIR/lib/gluegen-rt.jar" Hilbert "$@"
